name: Create additional release assets for new release

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download release
        id: download_release
        uses: robinraju/release-downloader@v1
        with:
          tag: ${{ GITHUB_REF }}
          tarBall: true
          extract: true

      - name: Download assets
        id: download_assets
        uses: robinraju/release-downloader@v1
        with:
          repository: 'prometheus/node_exporter'
          tag: ${{ GITHUB_REF }}
          fileName: 'node_exporter*.tar.gz'

      - name: Create assets
        id: create_assets
        run: |
          for file in node_exporter*.tar.gz; do
            filename=${file##*/}
            tar -xzvf $file
            rm $file
            mkdir -p ${{ GITHUB_REF }}/bin
            mv $filename/node_exporter ${{ GITHUB_REF }}bin/node_exporter
            tar -czvf $file ${{ GITHUB_REF }}
          done;

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          file_glob: true
          file: node_exporter*.tar.gz
          tag: ${{ GITHUB_REF }}
          overwrite: true
