name: Check for new release of prometheus node exporter and create new release of addon

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Get latest release
        id: get_release
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          owner: prometheus
          repo: node_exporter
          excludes: prerelease, draft

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_release.outputs.release }}
          release_name: Release ${{ steps.get_release.outputs.release }}
          body: |
            Changes in this Release
            - Updates node exporter binary to version ${{ steps.get_release.outputs.release }}
          draft: false
          prerelease: false
