name: Check for new release of prometheus node exporter and create new release of addon

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest

    outputs:
      addon_release: ${{ steps.addon_latest.outputs.release }}
      node_exporter_release: ${{ steps.node_exporter_latest.outputs.release }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Get latest addon release
        id: addon_latest
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          excludes: prerelease, draft

      - name: Get latest node exporterrelease
        id: node_exporter_latest
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          owner: prometheus
          repo: node_exporter
          excludes: prerelease, draft

  release:
    needs: check
    if: "${{ needs.check.outputs.addon_release != needs.check.outputs.node_exporter_release }}"
    runs-on: ubuntu-latest

    steps:
    - name: Create release
      id: create_release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ needs.check.outputs.node_exporter_release }}
        name: Release ${{ needs.check.outputs.node_exporter_release }}
        body: |
          Changes in this Release
          - Updates node exporter binary to version ${{ needs.check.outputs.node_exporter_release }}
        draft: false
        prerelease: false

    - name: Download release
      id: download_release
      uses: robinraju/release-downloader@v1
      with:
        tag: ${{ needs.check.outputs.node_exporter_release }}
        tarBall: true
        extract: true

    - name: Download assets
      id: download_assets
      uses: robinraju/release-downloader@v1
      with:
        repository: 'prometheus/node_exporter'
        tag: ${{ needs.check.outputs.node_exporter_release }}
        fileName: 'node_exporter*.tar.gz'

    - name: Create assets
      id: create_assets
      run: |
        for file in node_exporter*.tar.gz; do
          filename=${file##*/}
          tar -xzvf $file
          rm $file
          mkdir -p ${{ needs.check.outputs.node_exporter_release }}/bin
          mv $filename/node_exporter ${{ needs.check.outputs.node_exporter_release }}bin/node_exporter
          tar -czvf $file ${{ needs.check.outputs.node_exporter_release }}
        done;

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        file_glob: true
        file: node_exporter*.tar.gz
        tag: ${{ needs.check.outputs.node_exporter_release }}
        overwrite: true
